from abc import ABC, abstractmethod

from chemprop.v2.featurizers.molgraph import MolGraph


class MolGraphFeaturizerBase(ABC):
    @abstractmethod
    def __call__(self, *args, **kwargs) -> MolGraph:
        pass

    @property
    def shape(self) -> tuple[int, int]:
        """the feature dimension of the atoms and bonds, respectively, of `MolGraph`s generated by
        this featurizer"""
        return self.atom_fdim, self.bond_fdim
