from dataclasses import dataclass, field

from chemprop.v2.featurizers.atom import AtomFeaturizer, AtomFeaturizerProto
from chemprop.v2.featurizers.bond import BondFeaturizer, BondFeaturizerProto


@dataclass
class MolGraphFeaturizerMixin:
    atom_featurizer: AtomFeaturizerProto = field(default_factory=AtomFeaturizer)
    bond_featurizer: BondFeaturizerProto = field(default_factory=BondFeaturizer)
    bond_messages: bool = True

    def __post_init__(self):
        self.atom_fdim = len(self.atom_featurizer)
        self.bond_fdim = len(self.bond_featurizer)

    @property
    def shape(self) -> tuple[int, int]:
        """the feature dimension of the atoms and bonds, respectively, of `MolGraph`s generated by
        this featurizer"""
        return self.atom_fdim, self.bond_fdim
