# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '1.5.2.dev120+g53fdc0f.d20221015'
__version_tuple__ = version_tuple = (1, 5, 2, 'dev120', 'g53fdc0f.d20221015')
