from dataclasses import dataclass, field

import numpy as np
from rdkit.Chem.rdchem import Atom, Bond

from chemprop.featurizers.base import Featurizer
from chemprop.featurizers.atom import MultiHotAtomFeaturizer
from chemprop.featurizers.bond import MultiHotBondFeaturizer


@dataclass
class _MolGraphFeaturizerMixin:
    atom_featurizer: Featurizer[Atom, np.ndarray] = field(default_factory=MultiHotAtomFeaturizer)
    bond_featurizer: Featurizer[Bond, np.ndarray] = field(default_factory=MultiHotBondFeaturizer)

    def __post_init__(self):
        self.atom_fdim = len(self.atom_featurizer)
        self.bond_fdim = len(self.bond_featurizer)

    @property
    def shape(self) -> tuple[int, int]:
        """the feature dimension of the atoms and bonds, respectively, of `MolGraph`s generated by
        this featurizer"""
        return self.atom_fdim, self.bond_fdim
