DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS model;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  preferences JSON
);

CREATE TABLE model (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  model_name TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  class TEXT NOT NULL,
  stats JSON,
  epochs INTEGER NOT NULL DEFAULT 30,
  FOREIGN KEY (associated_user) REFERENCES user (id),
  completed BOOLEAN NOT NULL DEFAULT 0
);